// v1.3.0 feature layer; keeps v1.2.4 input handling intact (no re-render while typing)
const SCHEMA_VERSION=2;
db.schemaVersion=SCHEMA_VERSION;db.achievements=db.achievements||{evelin:{},silvio:{}};saveDb();
const STEP={'Leg Press':10,'Seated Row':5,'Lat Pulldown':5,'Leg Curl':5,'Reverse Pec Deck / Rear Delt':5,'Reverse Pec Deck':5,'Cable Face Pull':2.5,'Chest Press':5,'Leg Extension':5,'Pec Deck':5,'Shoulder Press':5,'Calf Raise Machine':5,'Incline Chest Press':5,'Lateral Raise Machine':2.5,'Hip Abductor Machine':5,'Abdominal Crunch Machine':5};
const ACH=[['first','Prvi trening'],['3','3 treninga'],['5','5 treninga'],['10','10 treninga'],['25','25 treninga'],['50','50 treninga'],['week3','3 treninga u jednom tjednu'],['streak4','4 uzastopna aktivna tjedna'],['weight','Prvi napredak u radnoj težini'],['reps','Prvi rekord ponavljanja'],['all','Sve planirane serije završene'],['v1000','Ukupni volumen 1.000 kg'],['v5000','Ukupni volumen 5.000 kg'],['v10000','Ukupni volumen 10.000 kg']];
const pSessions=p=>db.sessions.filter(s=>s.person===p),sKey=s=>s.date+(s.createdAt||''),prevSession=(p,w,before)=>pSessions(p).filter(s=>s.workout===w&&(!before||sKey(s)<sKey(before))).sort((a,b)=>sKey(b).localeCompare(sKey(a)))[0];
const volume=s=>s.exercises.reduce((n,e)=>n+(e.sets||[]).reduce((a,x)=>a+(x.done?(+x.weight||0)*(+x.reps||0):0),0),0),counts=s=>{const a=s.exercises.flatMap(e=>e.sets||[]);return[a.filter(x=>x.done).length,a.length]},range=t=>{const a=String(t||'').match(/\d+/g)?.map(Number)||[];return[a[0]||0,a[1]||a[0]||0]};
function weekStart(d){const x=new Date(d+'T12:00:00'),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x.toISOString().slice(0,10)}
function streak(p){const w=[...new Set(pSessions(p).map(s=>weekStart(s.date)))].sort().reverse();if(!w.length)return 0;let n=1;for(let i=1;i<w.length;i++)if((new Date(w[i-1])-new Date(w[i]))/86400000===7)n++;else break;return n}
function oldBests(p,name,before){return pSessions(p).filter(s=>sKey(s)<sKey(before)).flatMap(s=>s.exercises.filter(e=>e.name===name).flatMap(e=>e.sets.filter(x=>x.done))).reduce((o,x)=>({w:Math.max(o.w,+x.weight||0),r:Math.max(o.r,+x.reps||0)}),{w:0,r:0})}
function analyze(s){const prev=prevSession(s.person,s.workout,s),vol=volume(s),pvol=prev?volume(prev):null,progress=[],records=[];s.exercises.filter(e=>e.sets?.length).forEach(e=>{const old=oldBests(s.person,e.name,s),d=e.sets.filter(x=>x.done),w=Math.max(0,...d.map(x=>+x.weight||0)),r=Math.max(0,...d.map(x=>+x.reps||0));if(old.w&&w>old.w)progress.push(e.name);if(w>old.w)records.push(`${e.name}: ${w} kg`);else if(old.r&&r>old.r)records.push(`${e.name}: ${r} ponavljanja`)});return{prev,vol,pvol,progress:[...new Set(progress)],records}}
function recommend(e){const d=e.sets.filter(x=>x.done);if(!d.length)return'Bez preporuke dok nema završene serije.';const[min,max]=range(e.target),base=Math.max(...d.map(x=>+x.weight||0)),same=d.filter(x=>(+x.weight||0)===base),step=STEP[e.name]||2.5;if(same.length&&same.every(x=>x.reps>=max))return `Pokušaj ${base+step} kg (+${step} kg).`;if(d.filter(x=>x.reps<min).length>d.length/2)return `Razmisli o ${Math.max(0,base-step)} kg radi pravilnog raspona.`;return `Zadrži ${base} kg i gradi ponavljanja.`}
function unlock(p,date){const a=db.achievements[p]||(db.achievements[p]={}),ss=pSessions(p),v=ss.reduce((n,s)=>n+volume(s),0),weeks={};ss.forEach(s=>weeks[weekStart(s.date)]=(weeks[weekStart(s.date)]||0)+1);const latest=[...ss].sort((x,y)=>sKey(x).localeCompare(sKey(y))).at(-1),an=latest?analyze(latest):{progress:[],records:[]},[d,t]=latest?counts(latest):[0,0],c=ss.length,ok={first:c>=1,'3':c>=3,'5':c>=5,'10':c>=10,'25':c>=25,'50':c>=50,week3:Object.values(weeks).some(n=>n>=3),streak4:streak(p)>=4,weight:an.progress.length>0,reps:an.records.some(x=>x.includes('ponavljanja')),all:t>0&&d===t,v1000:v>=1000,v5000:v>=5000,v10000:v>=10000};ACH.forEach(([id])=>{if(ok[id]&&!a[id])a[id]=date});saveDb()}
const baseRender=render;render=function(){baseRender();const p=prevSession(person,workout);current().forEach((e,i)=>{if(!e[1])return;const pe=p?.exercises?.find(x=>x.name===e[0]);document.querySelectorAll(`.set-weight[data-k^="${i}-"]`).forEach((inp,j)=>{let note=inp.parentElement.querySelector('.previous-result');if(!note){note=document.createElement('small');note.className='previous-result';inp.insertAdjacentElement('afterend',note)}const s=pe?.sets?.[j];note.textContent=s?.done?`Prošli put: ${s.weight} kg × ${s.reps}`:'Nema prethodnog rezultata'})})};
function summary(s){const a=analyze(s),[d,t]=counts(s),diff=a.pvol==null?'Prvi zapis':`${a.vol-a.pvol>=0?'+':''}${Math.round(a.vol-a.pvol)} kg`;let m=document.getElementById('summaryModal');if(!m){m=document.createElement('div');m.id='summaryModal';m.className='info-modal';document.body.appendChild(m)}m.innerHTML=`<div class="info-backdrop" data-close></div><section class="info-sheet"><div class="info-sheet-head"><div><p class="eyebrow">TRENING SPREMLJEN</p><h2>Sažetak treninga</h2></div><button class="info-close" data-close>×</button></div><div class="summary-stats"><div><strong>${d}/${t}</strong><small>serija</small></div><div><strong>${Math.round(a.vol)} kg</strong><small>volumen</small></div><div><strong>${diff}</strong><small>vs. isti trening</small></div></div><h3>Napredak</h3><p>${a.progress.length?esc(a.progress.join(', ')):'Još nema usporedivog povećanja radne težine.'}</p><h3>Osobni rekordi</h3><p>${a.records.length?esc(a.records.join(' · ')):'Bez novog rekorda — kontinuitet je također napredak.'}</p><h3>Preporuka za sljedeći put</h3><ul class="recommend-list">${s.exercises.filter(e=>e.sets?.length).map(e=>`<li><strong>${esc(e.name)}:</strong> ${esc(recommend(e))}</li>`).join('')}</ul><div class="motivation">${d===t?'Odlično odrađen plan. Dosljednost gradi rezultat.':'Dobar trening. Bilježimo stvarno odrađeno i gradimo dalje korak po korak.'}</div></section>`;m.classList.add('open');m.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>m.classList.remove('open'))}
function saveV13(){const date=$('#sessionDate').value||today(),exercises=current().map((e,i)=>{const[name,sets,target,duration]=e;if(!sets){const v=draft[`${i}-cardio`]||{};return{name,duration:duration||null,target:null,done:!!v.d,sets:[]}}return{name,duration:null,target:target||null,sets:Array.from({length:sets},(_,j)=>{const v=draft[`${i}-${j}`]||{};return{weight:+v.w||0,reps:+v.r||0,done:!!v.d}})}}),s={id:String(Date.now()),person,workout,date,createdAt:new Date().toISOString(),exercises};db.sessions.push(s);saveDb();unlock(person,date);clearDraft();render();renderHistory();renderProgress();summary(s)}
$('#saveWorkoutBtn').onclick=saveV13;
function line(points){if(!points.length)return'<div class="empty-chart">Još nema dovoljno podataka.</div>';const w=320,h=150,p=18,v=points.map(x=>x.v),mn=Math.min(...v),mx=Math.max(...v),r=mx-mn||1,xy=points.map((x,i)=>[p+i*(w-2*p)/Math.max(1,points.length-1),h-p-(x.v-mn)*(h-2*p)/r]);return`<svg viewBox="0 0 ${w} ${h}" class="chart"><polyline points="${xy.map(x=>x.join(',')).join(' ')}" fill="none" stroke="currentColor" stroke-width="3"/>${xy.map((x,i)=>`<circle cx="${x[0]}" cy="${x[1]}" r="4" fill="currentColor"><title>${points[i].label}: ${points[i].v}</title></circle>`).join('')}</svg>`}
function bars(points){if(!points.length)return'<div class="empty-chart">Još nema podataka.</div>';const w=320,h=140,m=Math.max(1,...points.map(x=>x.v)),g=6,b=(w-20-g*(points.length-1))/points.length;return`<svg viewBox="0 0 ${w} ${h}" class="chart">${points.map((x,i)=>{const bh=(h-25)*x.v/m;return`<rect x="${10+i*(b+g)}" y="${h-18-bh}" width="${b}" height="${bh}" rx="3" fill="currentColor"><title>${x.label}: ${x.v}</title></rect>`}).join('')}</svg>`}
function renderProgress(){const ss=pSessions(person),v=ss.reduce((n,s)=>n+volume(s),0),wn=ss.filter(s=>weekStart(s.date)===weekStart(today())).length;$('#progressStats').innerHTML=`<div><strong>${ss.length}</strong><small>treninga</small></div><div><strong>${wn}</strong><small>ovaj tjedan</small></div><div><strong>${streak(person)}</strong><small>aktivna tjedna</small></div><div><strong>${Math.round(v)} kg</strong><small>ukupni volumen</small></div>`;const names=[...new Set(Object.values(PROGRAM[person]).flat().filter(e=>e[1]).map(e=>e[0]))].sort(),sel=$('#exerciseSelect'),old=sel.value;sel.innerHTML=names.map(n=>`<option>${esc(n)}</option>`).join('');if(names.includes(old))sel.value=old;const name=sel.value||names[0],metric=$('#metricSelect').value||'weight',pts=[...ss].sort((a,b)=>a.date.localeCompare(b.date)).map(s=>{const e=s.exercises.find(e=>e.name===name),d=e?.sets?.filter(x=>x.done)||[];return d.length?{label:fmt(s.date),v:metric==='volume'?d.reduce((n,x)=>n+x.weight*x.reps,0):Math.max(...d.map(x=>x.weight))}:null}).filter(Boolean);$('#exerciseChart').innerHTML=line(pts);const wk={};ss.forEach(s=>wk[weekStart(s.date)]=(wk[weekStart(s.date)]||0)+1);$('#weeklyChart').innerHTML=bars(Object.entries(wk).sort().slice(-8).map(([label,v])=>({label,v})));const a=db.achievements[person]||{};$('#achievementList').innerHTML=ACH.map(([id,l])=>`<div class="achievement ${a[id]?'unlocked':''}"><span>${a[id]?'✓':'○'}</span><div><strong>${l}</strong><small>${a[id]?fmt(a[id]):'Još nije otključano'}</small></div></div>`).join('')}
$('#exerciseSelect').onchange=renderProgress;$('#metricSelect').onchange=renderProgress;document.querySelector('[data-tab="progress"]').addEventListener('click',renderProgress);
$('#exportBtn').onclick=()=>{const out={schemaVersion:SCHEMA_VERSION,exportedAt:new Date().toISOString(),sessions:db.sessions,achievements:db.achievements};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download=`trening-backup-${today()}.json`;a.click()};
$('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.sessions))throw 0;db={schemaVersion:SCHEMA_VERSION,sessions:x.sessions,achievements:x.achievements||{evelin:{},silvio:{}}};saveDb();['evelin','silvio'].forEach(p=>{const last=pSessions(p).sort((a,b)=>sKey(a).localeCompare(sKey(b))).at(-1);if(last)unlock(p,last.date)});render();renderHistory();renderProgress();toast('Podaci uvezeni.')}catch{toast('Neispravna JSON datoteka.')}};r.readAsText(f)};
render();renderProgress();
